name: Publish to NPM

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    environment: npm-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"

      - name: Set up Volta
        uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4

      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ".yarn/cache"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install

      - name: Publish to NPM
        run: yarn publish --non-interactive
